/** Semantic UI component kinds exposed by the UIKit layer. */
export type UIKind =
  | "button"
  | "link"
  | "input"
  | "textarea"
  | "checkbox"
  | "radio"
  | "select"
  | "combobox"
  | "date-picker"
  | "file-picker"
  | "slider"
  | "menu"
  | "menu-item"
  | "dialog"
  | "alert"
  | "toast"
  | "tooltip"
  | "tabs"
  | "tab"
  | "table"
  | "grid"
  | "list"
  | "form"
  | "wizard"
  | "pagination"
  | "search"
  | "rich-text-editor"
  | "code-editor"
  | "virtualized-list"
  | "canvas-control"
  | "iframe-component"
  | "shadow-component";

/** Coarse viewport region used for layout-scoped queries. */
export type LayoutRegion =
  | "top"
  | "bottom"
  | "left"
  | "right"
  | "center"
  | "header"
  | "footer"
  | "main";
