// Bundles the in-page kernel to an IIFE and embeds it as a TypeScript string
// module so the Node-side SDK can inject it through any runtime adapter.
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const result = await build({
  entryPoints: [join(pkgRoot, "src/kernel/global.ts")],
  bundle: true,
  format: "iife",
  target: "es2020",
  minify: true,
  write: false,
  legalComments: "none"
});

const source = result.outputFiles[0].text;
if (/\beval\s*\(|new Function\s*\(/.test(source)) {
  throw new Error("kernel bundle must not contain eval or new Function");
}

const genDir = join(pkgRoot, "src/generated");
mkdirSync(genDir, { recursive: true });
writeFileSync(
  join(genDir, "kernel-source.ts"),
  `// Generated by scripts/build-kernel.mjs. Do not edit.\nexport const KERNEL_SOURCE: string = ${JSON.stringify(source)};\n`
);
console.log(`kernel bundle: ${source.length} bytes`);
